version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  api:
    build: ./app
    command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done; ls; ./out/goproj"
    ports:
      - "8080:8080"
    depends_on:
      - db